# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0002_subject_max_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='sub1_marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='student',
            name='sub2_marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='student',
            name='sub3_marks',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
