# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage', '0003_auto_20171017_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub1_attaindance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='student',
            name='sub2_attaindance',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='student',
            name='sub3_attaindance',
            field=models.IntegerField(default=10),
        ),
    ]
